# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('sampleid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sample', models.CharField(max_length=30)),
                ('chr', models.CharField(max_length=6)),
                ('pos', models.CharField(max_length=30)),
                ('ref', models.CharField(max_length=2)),
                ('alt', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=10)),
                ('gq', models.CharField(max_length=10)),
                ('gene', models.CharField(max_length=10)),
            ],
        ),
    ]
