# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='gq',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='type',
            new_name='caller',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='sampleid',
            new_name='sample_id',
        ),
        migrations.AddField(
            model_name='results',
            name='end_pos',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='results',
            name='exonic_func',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='results',
            name='func',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='results',
            name='gt',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='results',
            name='size',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='results',
            name='sv_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='results',
            name='total_reads',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
