# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20160602_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='ab',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterModelTable(
            name='results',
            table='Results',
        ),
    ]
