# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20160602_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='ad',
            field=models.CharField(default='', max_length=5),
        ),
    ]
