# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primers',
            fields=[
                ('primer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gene', models.CharField(default='', max_length=10)),
                ('exon', models.CharField(default='', max_length=10)),
                ('direction', models.CharField(default='', max_length=1)),
                ('version', models.IntegerField(default=None)),
                ('primer_seq', models.CharField(default='', max_length=30)),
                ('chrom', models.CharField(default='', max_length=2)),
                ('m13_tag', models.CharField(default='', max_length=1)),
                ('batch', models.CharField(default='', max_length=30)),
                ('project', models.CharField(default='', max_length=200)),
                ('order_date', models.CharField(default='', max_length=20)),
                ('frag_size', models.IntegerField(default=None)),
                ('anneal_temp', models.CharField(default='', max_length=10)),
                ('other', models.CharField(default='', max_length=200)),
                ('snp_check', models.IntegerField(default=None)),
                ('no_snps', models.IntegerField(default=None)),
                ('rs', models.CharField(default='', max_length=20)),
                ('hgvs', models.CharField(default='', max_length=20)),
                ('freq', models.CharField(default='', max_length=200)),
                ('ss', models.CharField(default='', max_length=100)),
                ('ss_proj', models.CharField(default='', max_length=200)),
                ('other2', models.CharField(default='', max_length=200)),
                ('action_to_take', models.CharField(default='', max_length=100)),
                ('check_by', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'Primers',
            },
        ),
    ]
