# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primerdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('ActionId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Datetime', models.DateTimeField()),
                ('Info', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=6)),
                ('Previous_file', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'LoginRecords',
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gene', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['gene', 'gene_id'],
                'db_table': 'Genes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrimers',
            fields=[
                ('primerid', models.IntegerField(blank=True, db_index=True)),
                ('gene', models.CharField(max_length=10)),
                ('exon', models.CharField(max_length=3)),
                ('direction', models.CharField(max_length=1)),
                ('name', models.CharField(default='', max_length=30)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('primer_seq', models.CharField(max_length=30)),
                ('chrom', models.CharField(max_length=2)),
                ('start', models.CharField(default=None, max_length=30)),
                ('end', models.CharField(default=None, max_length=30)),
                ('m13_tag', models.CharField(blank=True, max_length=1)),
                ('batch', models.CharField(blank=True, max_length=30)),
                ('project', models.CharField(default='', max_length=200)),
                ('order_date', models.DateField(blank=True)),
                ('frag_size', models.IntegerField(blank=True)),
                ('anneal_temp', models.CharField(blank=True, max_length=10)),
                ('other', models.CharField(blank=True, max_length=200)),
                ('no_snps', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical primers',
            },
        ),
        migrations.CreateModel(
            name='SNPs',
            fields=[
                ('snp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('snp_check', models.IntegerField(default='')),
                ('rs', models.CharField(default='', max_length=20)),
                ('hgvs', models.CharField(default='', max_length=20)),
                ('freq', models.CharField(default='', max_length=200)),
                ('ss', models.CharField(default='', max_length=100)),
                ('ss_proj', models.CharField(default='', max_length=200)),
                ('other2', models.CharField(default='', max_length=200)),
                ('action_to_take', models.CharField(default='', max_length=100)),
                ('check_by', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'SNPs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='primers',
            old_name='primer_id',
            new_name='primerid',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='action_to_take',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='check_by',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='hgvs',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='rs',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='snp_check',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='ss_proj',
        ),
        migrations.AddField(
            model_name='primers',
            name='end',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='primers',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='primers',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='anneal_temp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='primers',
            name='batch',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='chrom',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='primers',
            name='direction',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='primers',
            name='exon',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='primers',
            name='frag_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='primers',
            name='gene',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='primers',
            name='m13_tag',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='primers',
            name='no_snps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='primers',
            name='order_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='primers',
            name='other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='primers',
            name='primer_seq',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
