# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerdb', '0002_auto_20160330_0912'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='AuditLog',
        ),
    ]
